# Generated by Django 5.2.5 on 2025-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('BOD', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(default='New', max_length=20)),
                ('Added_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
