# Generated by Django 5.2.5 on 2025-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
